### PR TITLE
Diamond

### PR DESCRIPTION
**Pull request by wwood**
Please cast quite a critical eye - as you know I am only learning this stuff. ta.

### CODE REVIEW

**Comment by davexunit** [comment]
There's all sorts of irrelevant commits from other people in there.  Could you make a branch off of master with only your one patch on top?

**Comment by wwood** [comment]
I could if you like, but this line was forked off the git.savannah master
branch. So I think that if this repo is updated all will be as you want.
The contribution here is only the 1 final commit.

**Comment by pjotrp** [comment]
It just means my master is out of date ;). I'll sync it.

**Comment by pjotrp** [comment]
After updating the tree I created a new pull request. This is what the change contains:

https://github.com/genenetwork/guix/pull/8/files

**Comment by wwood** [comment]
moved this conversation to guix-devel mailing list.

**Pull request closed without merging**
